## Post-process output from CNN
setwd("~/SSA_model/CNN/simbed/")

rm(list = ls())
source("./source/create_model.R")
source("./source/custom_loss_function.R")

library(mvtnorm) 
library(keras)
reticulate::use_condaenv("myenv", required = TRUE)
library(tensorflow)
library(ggplot2)

## Flags
output_var <- "all" # "friction" # "grounding_line" # "bed_elevation
# sim_beds <- T
save_plots <- T

## Read data
data_date <- "20240320"
sets <- 6:7
# setf <- formatC(set, width=2, flag="0")
setsf <- paste0("sets", sets[1], "-", sets[length(sets)])


# if (sim_beds) {
data_dir <- paste0("./training_data/", setsf)
output_dir <- paste0("./output/", output_var, "/", setsf)
test_data <- readRDS(file = paste0(data_dir, "/test_data_", data_date, ".rds"))
ssa_steady <- readRDS(file = paste("./training_data/initial_conds/ssa_steady_20220329.rds", sep = ""))
domain <- ssa_steady$domain

## Load the model
test_input <- test_data$input

if (output_var == "friction") {
    test_output <- test_data$fric_coefs
} else if (output_var == "grounding_line") {
    test_output <- test_data$grounding_line
} else if (output_var == "bed") {
    test_output <- test_data$bed_coefs
} else if (output_var == "all") {
    test_output <- cbind(test_data$fric_coefs, test_data$bed_coefs, test_data$grounding_line)
} else {
    print("Output variable should be either 'friction', 'bed' or 'grounding_line'.")
}

input_dim <- dim(test_input)[2:4]
output_dim <- ncol(test_output)
model <- create_model(input_dim = input_dim, output_dim = output_dim)

# Display the model's architecture
summary(model)

## Plot the loss
history <- readRDS(file = paste0(output_dir, "/history_", data_date, ".rds"))
# history %>% plot() #+
# coord_cartesian(xlim = c(1, epochs))

plot(history$metrics$loss[2:100], type = "l")
lines(history$metrics$val_loss[2:100], col = "red")
legend("topright", legend = c("Training", "Validation"), col = c("black", "red"), lty = 1, cex = 0.8)

plot_dir <- paste0("./plots/", output_var, "/", setsf)

if (save_plots) {

    if (!dir.exists(plot_dir)) {
        dir.create(plot_dir)
    }

    png(paste0(plot_dir, "/loss_", output_var, ".png"), width = 1000, height = 500)
    plot(history$metrics$loss[2:100], type = "l")
    lines(history$metrics$val_loss[2:100], col = "red")
    legend("topright", legend = c("Training", "Validation"), col = c("black", "red"), lty = 1, cex = 0.8)
    dev.off()
}

###################################
##        Mean prediction        ##   
###################################

## Reload model from checkpoint
checkpoint_path <- paste0(output_dir, "/checkpoints/cp-{epoch:04d}.ckpt")
checkpoint_dir <- fs::path_dir(checkpoint_path)

checkpt <- which.min(history$metrics$val_loss) # c(69)
# for (checkpt in checkpts) {
if (!is.null(checkpt)) {
    ## Load the model from checkpt
    cp_restart <- paste0(output_dir, "/checkpoints/cp-", formatC(checkpt, width = 4, flag = "0"), ".ckpt")
    # latest <- tf$train$latest_checkpoint(checkpoint_dir)
    load_model_weights_tf(model, cp_restart)
} else {
    latest <- tf$train$latest_checkpoint(checkpoint_dir)
    load_model_weights_tf(model, latest)
}

## Predict
pred_output <- model %>% predict(test_input)

## Plot the predicted friction coefs generated by these basis functions

if (output_var == "all") {
    fric_basis_mat <- test_data$fric_basis_mat
    bed_basis_mat <- test_data$bed_basis_mat
    n_fric_basis <- ncol(fric_basis_mat)
    n_bed_basis <- ncol(bed_basis_mat)

    ## Un-standardise output
    pred_fric_coefs <- pred_output[, 1:n_fric_basis] * test_data$sd_fric_coefs + test_data$mean_fric_coefs
    pred_bed_coefs <- pred_output[, (n_fric_basis+1):(n_fric_basis+n_bed_basis)] * test_data$sd_bed_coefs + test_data$mean_bed_coefs
    pred_gl <- pred_output[, (n_fric_basis+n_bed_basis+1):ncol(pred_output)] * test_data$sd_gl + test_data$mean_gl

    test_fric_coefs <- test_output[, 1:n_fric_basis] * test_data$sd_fric_coefs + test_data$mean_fric_coefs
    test_bed_coefs <- test_output[, (n_fric_basis+1):(n_fric_basis+n_bed_basis)] * test_data$sd_bed_coefs + test_data$mean_bed_coefs
    test_gl <- test_output[, (n_fric_basis+n_bed_basis+1):ncol(pred_output)] * test_data$sd_gl + test_data$mean_gl

    ## Compute predicted vs original friction -- this needs more work!!
    pred_fric <- fric_basis_mat %*% t(pred_fric_coefs)
    test_fric <- fric_basis_mat %*% t(test_fric_coefs)

    ## Compute predicted vs original bed elevations
    pred_bed_demean <- bed_basis_mat %*% t(pred_bed_coefs)
    test_bed_demean <- bed_basis_mat %*% t(test_bed_coefs)


} else {
    stop("Output not available for this variable.")
}

######################################
##        Quantile prediction       ##
######################################
quantiles <- c(0.05, 0.95)
pred_quantiles <- list()

for (q in 1:length(quantiles)) {
    quantile <- quantiles[q]
    output_dir_quantile <- paste0("./output/", output_var, "/", setsf, "/quantile", quantile*100)

    model_quantile <- create_model_quantile(input_dim = input_dim, output_dim = output_dim, quantile = quantile)

    history_quantile <- readRDS(file = paste0(output_dir_quantile, "/history_", data_date, ".rds"))
    # history %>% plot() #+
    # coord_cartesian(xlim = c(1, epochs))
    par(mfrow = c(2,1))
    plot(history_quantile$metrics$loss[2:100], type = "l", 
            xlab = "Iteration", ylab = "Loss",
            main = paste0("Loss when training the", quantile*100, "th quantile"))
    lines(history_quantile$metrics$val_loss[2:100], col = "red")
    legend("topright", legend = c("Training", "Validation"), 
            col = c("black", "red"), lty = 1, cex = 0.8)

    ## Reload model for quantile from checkpoint
    checkpoint_path_quantile <- paste0(output_dir_quantile, "/checkpoints/cp-{epoch:04d}.ckpt")
    checkpoint_dir_quantile <- fs::path_dir(checkpoint_path_quantile)

    checkpt_quantile <- which.min(history_quantile$metrics$val_loss) # c(69)
    # for (checkpt in checkpts) {
    if (!is.null(checkpt_quantile)) {
        ## Load the model from checkpt
        cp_restart_quantile <- paste0(output_dir_quantile, "/checkpoints/cp-", formatC(checkpt_quantile, width = 4, flag = "0"), ".ckpt")
        # latest <- tf$train$latest_checkpoint(checkpoint_dir)
        load_model_weights_tf(model_quantile, cp_restart_quantile)
    } else {
        latest_cp_quantile <- tf$train$latest_checkpoint(checkpoint_dir_quantile)
        load_model_weights_tf(model_quantile, latest_cp_quantile)
    }

    ## Predict
    pred_output_quantile <- model_quantile %>% predict(test_input)

    ## Un-standardise output
    pred_fric_coefs_quantile <- pred_output_quantile[, 1:n_fric_basis] * test_data$sd_fric_coefs + test_data$mean_fric_coefs
    pred_bed_coefs_quantile <- pred_output_quantile[, (n_fric_basis+1):(n_fric_basis+n_bed_basis)] * test_data$sd_bed_coefs + test_data$mean_bed_coefs
    pred_gl_quantile <- pred_output_quantile[, (n_fric_basis+n_bed_basis+1):ncol(pred_output_quantile)] * test_data$sd_gl + test_data$mean_gl

    # pred_quantiles[[q]] <- list(fric = pred_fric_quantile, bed = pred_bed_quantile, gl = pred_gl_quantile)
    pred_quantiles[[q]] <- list(fric = pred_fric_coefs_quantile, 
                                bed = pred_bed_coefs_quantile, 
                                gl = pred_gl_quantile)
    
}

########### end quantile ################

## Calculate quantiles of the bed and friction based on 
## the quantiles of the basis function coefficients

### Friction
z_val <- qnorm(0.95)
fric_sd1 <- (pred_fric_coefs - pred_quantiles[[1]]$fric) / z_val # distance from mean to lower quantile
fric_sd2 <- (pred_quantiles[[2]]$fric - pred_fric_coefs) / z_val # distance from mean to upper quantile
fric_avg_sd <- (fric_sd1 + fric_sd2)/2 # this is the "point-wise" standard deviation 

## Now sample lots of basis coefficients from this distribution
## Maybe for each test output sample, we can sample 1000 basis coefficients
n_fric_basis <- ncol(fric_basis_mat)
fric_coef_samples <- list()
fric_lq <- list()
fric_uq <- list()

S <- 1000

for (r in 1:nrow(test_output)) { ## need to parallelise this so that it's faster
    # fric_coef_samples[[s]] <- rnorm(n_fric_basis, mean = pred_fric_coefs[s, ], sd = avg_sd[s, ]) # might need to sample more than 1 later
    # system.time(fric_coef_samples <- rmvnorm(1000, 
    #                                         mean = pred_fric_coefs[r, ], 
    #                                         sigma = diag(fric_avg_sd[r, ]^2))) # might need to sample more than 1 later
    
    system.time(fric_coef_samples_list <- lapply(1:S, function(i) rnorm(n_fric_basis, 
                                                                    mean = pred_fric_coefs[r, ], 
                                                                    sd = fric_avg_sd[r, ])))
    fric_coef_samples <- t(matrix(unlist(fric_coef_samples_list), nrow = n_fric_basis, ncol = S))
    fric_samples <- fric_basis_mat %*% t(fric_coef_samples)

    ## Now take the pointwise quantiles
    fric_lq[[r]] <- apply(fric_samples, 1, quantile, probs = 0.05)
    fric_uq[[r]] <- apply(fric_samples, 1, quantile, probs = 0.95)
    
}

### Bed elevation

#### Add bed trend to the predicted oscillations
bed_obs <- readRDS(file = paste0("./training_data/bed_obs_", data_date, ".rds"))
df <- data.frame(obs_locations = domain[bed_obs$locations], bed_elev = bed_obs$obs)
bed.fit <- loess(bed_elev ~ obs_locations, data = df, span = 0.25, 
                    control = loess.control(surface = "direct")) 
bed_mean <- predict(bed.fit, newdata = data.frame(obs_locations = domain))
bed_mean_mat <- matrix(rep(bed_mean), nrow = length(bed_mean), ncol = ncol(pred_bed_demean))

pred_bed <- pred_bed_demean + bed_mean_mat
test_bed <- test_bed_demean + bed_mean_mat

#### Quantiles for bed oscillations
z_val <- qnorm(0.95)
bed_sd1 <- (pred_bed_coefs - pred_quantiles[[1]]$bed) / z_val # distance from mean to lower quantile
bed_sd2 <- (pred_quantiles[[2]]$bed - pred_bed_coefs) / z_val # distance from mean to upper quantile
bed_avg_sd <- (bed_sd1 + bed_sd2)/2 # this is the "point-wise" standard deviation 

## Now sample lots of basis coefficients from this distribution
## Maybe for each test output sample, we can sample 1000 basis coefficients
n_bed_basis <- ncol(bed_basis_mat)
bed_coef_samples <- list()
bed_lq <- list()
bed_uq <- list()

bed_mean_mat <- matrix(rep(bed_mean), nrow = length(bed_mean), ncol = S)
for (r in 1:nrow(test_output)) {
    system.time(bed_coef_samples_list <- lapply(1:S, function(i) rnorm(n_bed_basis, 
                                                                    mean = pred_bed_coefs[r, ], 
                                                                    sd = bed_avg_sd[r, ])))
    bed_coef_samples <- t(matrix(unlist(bed_coef_samples_list), nrow = n_bed_basis, ncol = S))
    bed_samples_demean <- bed_basis_mat %*% t(bed_coef_samples)
    bed_samples <- bed_samples_demean + bed_mean_mat

    ## Now take the pointwise quantiles
    bed_lq[[r]] <- apply(bed_samples, 1, quantile, probs = 0.05)
    bed_uq[[r]] <- apply(bed_samples, 1, quantile, probs = 0.95)
    
}

### Grounding line
pred_gl_lq <- pred_quantiles[[1]]$gl
pred_gl_uq <- pred_quantiles[[2]]$gl

######################################
##      Comparison with truth       ##
######################################

## True parameter values for comparison
true_fric <- test_data$true_fric
true_bed <- test_data$true_bed
true_gl <- test_data$true_gl #* test_data$sd_gl + test_data$mean_gl

## Scaling units for friction coefficients
# secpera <- 31556926
# fric_scale <- 1e6 * secpera^(1/3)
# true_fric <- true_fric/fric_scale

## Choose random samples from test set for plotting
samples <- sample(1:nrow(test_output), 6)

# # if (output_var == "grounding_line" | output_var == "all") {
#     ## Grounding line plot
#     for (i in 1:length(samples)) {
#         par(mar = c(6, 8, 4, 2))
#         # gl <- test_data$grounding_line[i] / 800 * 2001
#         plot_domain <- 1:length(domain) # ceiling(gl)
#         plot(true_gl[i, ], 1:20,
#             type = "l", lwd = 2, 
#             xlab = "Grounding line (km)", ylab = "Time (year)", cex.axis = 3, cex.lab = 4
#         )
#         # lines(domain[plot_domain] / 1000, test_fric[i, ], lwd = 2, col = "blue")
#         lines(pred_gl[i, ], 1:20, lwd = 2, col = "red")
#         lines(pred_gl_lq[i, ], 1:20, lty = 3, lwd = 2, col = "skyblue")
#         lines(pred_gl_uq[i, ], 1:20, lty = 3, lwd = 2, col = "skyblue")
        
#         # abline(v = test_data$test_gl[i], lwd = 3, lty = 2)
#     }
# # }

if (save_plots) {
    
    ## Friction plots
    png(paste0(plot_dir, "/pred_vs_true_fric", checkpt, ".png"), width = 2000, height = 1200)

    par(mfrow = c(length(samples) / 2, 2))
    for (i in 1:length(samples)) {
        par(mar = c(6, 8, 4, 2))
        gl <- test_data$grounding_line[i] / 800 * 2001
        plot_domain <- 1:length(domain) # ceiling(gl)

        plot(domain[plot_domain]/1000, true_fric[i, ], type = "l", 
            ylab = "Friction (unit)", xlab = "Domain (km)", 
            cex.axis = 3, cex.lab = 4)
        lines(domain[plot_domain]/1000, pred_fric[, i], col = "red")
        lines(domain[plot_domain]/1000, fric_lq[[i]], lty = 1, col = "skyblue")
        lines(domain[plot_domain]/1000, fric_uq[[i]], lty = 1, col = "skyblue")
        abline(v = test_data$test_gl[i], lty = 1, lwd = 3)
    }

    dev.off()

    ## Bed plot
    png(paste0(plot_dir, "/pred_vs_true_bed", checkpt, ".png"), width = 2000, height = 2000)
    par(mfrow = c(length(samples) / 2, 2))

    # par(mfrow = c(length(samples) / 2, 2))
    # for (i in 1:length(samples)) {
    #     plot(domain/1000, true_bed[i, ], type = "l", ylab = "Friction")
    #     lines(domain/1000, pred_bed[, i], col = "red")
    #     lines(domain/1000, bed_lq[[i]], lty = 1, col = "skyblue")
    #     lines(domain/1000, bed_uq[[i]], lty = 1, col = "skyblue")
    # }

    # if (output_var == "bed" | output_var == "all") {
        for (i in 1:length(samples)) {
            par(mar = c(6, 8, 4, 2))
            # gl <- test_data$grounding_line[i] / 800 * 2001
            plot_domain <- 1:length(domain) # ceiling(gl)
            plot(domain[plot_domain] / 1000, true_bed[i, plot_domain],
                type = "l", lwd = 2, col = "black",
                ylab = "Bed (m)", xlab = "Domain (km)", cex.axis = 3, cex.lab = 4
            )
            # lines(domain[plot_domain] / 1000, test_bed[plot_domain, i], lwd = 2, col = "blue")
            lines(domain[plot_domain] / 1000, pred_bed[plot_domain, i], lwd = 3, col = "red")
            lines(domain[plot_domain] / 1000, bed_lq[[i]], lty = 1, lwd = 3, col = "skyblue")
            lines(domain[plot_domain] / 1000, bed_uq[[i]], lty = 1, lwd = 3, col = "skyblue")
            
            abline(v = test_data$test_gl[i], lty = 1, lwd = 3)
        }
    # }
    dev.off()


    # # if (output_var == "friction" | output_var == "all") {
    #     ## Friction plot
    #     for (i in 1:length(samples)) {
    #         par(mar = c(6, 8, 4, 2))
    #         gl <- test_data$grounding_line[i] / 800 * 2001
    #         plot_domain <- 1:length(domain) # ceiling(gl)
    #         plot(domain[plot_domain] / 1000, true_fric[i, plot_domain],
    #             type = "l", lwd = 2, 
    #             ylab = "Friction (unit)", xlab = "Domain (km)", cex.axis = 3, cex.lab = 4
    #         )
    #         # lines(domain[plot_domain] / 1000, test_fric[plot_domain, i], lwd = 2, col = "blue")
    #         lines(domain[plot_domain] / 1000, pred_fric[plot_domain, i], lwd = 2, col = "red")
    #         lines(domain[plot_domain] / 1000, pred_fric_lq[plot_domain, i], lty = 2, lwd = 2, col = "skyblue")
    #         lines(domain[plot_domain] / 1000, pred_fric_uq[plot_domain, i], lty = 2, lwd = 2, col = "skyblue")
            
    #         abline(v = test_data$test_gl[i], lty = 1, lwd = 3)
    #     }
    # # }
    # dev.off()

    ## Grounding line plot
    
    png(paste0(plot_dir, "/pred_vs_true_gl", checkpt, ".png"), width = 2000, height = 2000)
    par(mfrow = c(length(samples) / 2, 2))

    for (i in 1:length(samples)) {
        par(mar = c(6, 8, 4, 2))
        # gl <- test_data$grounding_line[i] / 800 * 2001
        plot_domain <- 1:length(domain) # ceiling(gl)
        plot(true_gl[i, ], 1:20,
            type = "l", lwd = 2, 
            xlab = "Grounding line (km)", ylab = "Time (year)", cex.axis = 3, cex.lab = 4
        )
        # lines(domain[plot_domain] / 1000, test_fric[i, ], lwd = 2, col = "blue")
        lines(pred_gl[i, ], 1:20, lwd = 2, col = "red")
        lines(pred_gl_lq[i, ], 1:20, lty = 1, lwd = 3, col = "skyblue")
        lines(pred_gl_uq[i, ], 1:20, lty = 1, lwd = 3, col = "skyblue")
        
        # abline(v = test_data$test_gl[i], lwd = 3, lty = 2)
    }

    dev.off()
}

############################################# RMSE ##################################################
rmse <- function(truth, pred) {
    sqrt(mean((truth - pred)^2))
}

total_rmse <- 0
if (output_var == "friction") {## Post-process output from CNN
    truth <- test_fric
    pred <- pred_fric
} else if (output_var == "grounding_line") {
   truth <- test_gl
   pred <- pred_gl
} else if (output_var == "bed") {
    truth <- test_bed
    pred <- pred_bed
} else if (output_var == "all") {
    truth <- cbind(test_fric, test_bed)
    pred <- cbind(pred_fric, pred_bed)
} else {
    print("Output variable should be either 'friction', 'bed' or 'grounding_line'.")
}

for (s in 1:ncol(truth)) {
    total_rmse <- total_rmse + rmse(truth[, s], pred[, s])
}
cat("RMSE: ", total_rmse / ncol(truth), "\n") # normalise by number of simulations in the test set

# }

