## Post-process output from CNN
setwd("~/SSA_model/CNN/simbed/")

rm(list = ls())
source("./source/create_model.R")
source("./source/posterior_loss.R")

library(mvtnorm) 
library(keras)
reticulate::use_condaenv("myenv", required = TRUE)
library(tensorflow)
library(ggplot2)

## Flags
# output_var <- "all" # "friction" # "grounding_line" # "bed_elevation
save_pred <- T
save_plots <- T
log_transform <- T
test_on_train <- F

## Read data
data_date <- "20240320"
sets <- 1:50 #6:20
# setf <- formatC(set, width=2, flag="0")
setsf <- paste0("sets", sets[1], "-", sets[length(sets)])

# if (sim_beds) {
data_dir <- paste0("./training_data/", setsf)
output_dir <- paste0("./output/posterior/", setsf)
test_data <- readRDS(file = paste0(data_dir, "/test_data_", data_date, ".rds"))

if (test_on_train) {
    train_data <- readRDS(file = paste0(data_dir, "/train_data_", data_date, ".rds"))
}

ssa_steady <- readRDS(file = paste("./training_data/initial_conds/ssa_steady_20220329.rds", sep = ""))
domain <- ssa_steady$domain

## Load the model
test_input <- test_data$input
test_output <- cbind(test_data$fric_coefs, test_data$bed_coefs, test_data$grounding_line)

input_dim <- dim(test_data$input)[2:4]
n_basis_funs <- dim(test_data$fric_coefs)[2]
n_gl <- dim(test_data$grounding_line)[2]
n_mean_elements <- n_basis_funs * 2 + n_gl
n_chol_elements <- (n_basis_funs * 2 + n_gl) + (n_basis_funs - 1) * 2 + (n_gl - 1) # diagonal + lower-diag elements
output_dim <- n_mean_elements + n_chol_elements  # THIS NEEDS TO CHANGE TO THE TOTAL NUMBER OF BASIS FUNCTIONS + COVARIANCE PARAMETERS

model <- create_model_posterior(input_dim = input_dim, 
                                output_dim = output_dim,
                                n_basis_funs = n_basis_funs,
                                n_gl = n_gl)
# Display the model's architecture
summary(model)

## Plot the loss
history <- readRDS(file = paste0(output_dir, "/history_", data_date, ".rds"))
# history %>% plot() #+
# coord_cartesian(xlim = c(1, epochs))

plot(history$metrics$loss, type = "l")
lines(history$metrics$val_loss, col = "red")
legend("topright", legend = c("Training", "Validation"), col = c("black", "red"), lty = 1, cex = 0.8)

plot_dir <- paste0("./plots/posterior/", setsf)

if (save_plots) {

    if (!dir.exists(plot_dir)) {
        dir.create(plot_dir)
    }

    png(paste0(plot_dir, "/loss.png"), width = 1000, height = 500)
    plot(history$metrics$loss[2:50], type = "l")
    lines(history$metrics$val_loss[2:50], col = "red")
    legend("topright", legend = c("Training", "Validation"), col = c("black", "red"), lty = 1, cex = 0.8)
    dev.off()
}

###################################
##        Mean prediction        ##   
###################################

## Reload model from checkpoint
checkpoint_path <- paste0(output_dir, "/checkpoints/cp-{epoch:04d}.ckpt")
checkpoint_dir <- fs::path_dir(checkpoint_path)

checkpt <- which.min(history$metrics$val_loss) # c(69)
# for (checkpt in checkpts) {
if (!is.null(checkpt)) {
    ## Load the model from checkpt
    cp_restart <- paste0(output_dir, "/checkpoints/cp-", formatC(checkpt, width = 4, flag = "0"), ".ckpt")
    # latest <- tf$train$latest_checkpoint(checkpoint_dir)
    load_model_weights_tf(model, cp_restart)
} else {
    latest <- tf$train$latest_checkpoint(checkpoint_dir)
    load_model_weights_tf(model, latest)
}

## Predict
if (test_on_train) {
    train_subset <- train_data$input[1:100,,,]
    pred_output <- model %>% predict(train_subset)
} else {
    pred_output <- model %>% predict(test_input)
}
# pred_output <- model %>% predict(test_input)

## Plot the predicted friction coefs generated by these basis functions

# if (output_var == "all") {
    fric_basis_mat <- test_data$fric_basis_mat
    bed_basis_mat <- test_data$bed_basis_mat
    n_fric_basis <- ncol(fric_basis_mat)
    n_bed_basis <- ncol(bed_basis_mat)

    pred_mean <- pred_output[, 1:n_mean_elements]
    pred_chol <- pred_output[, (n_mean_elements+1):ncol(pred_output)]
    
    ## Un-standardise output
    pred_fric_coefs <- pred_mean[, 1:n_fric_basis] * test_data$sd_fric_coefs + test_data$mean_fric_coefs
    pred_bed_coefs <- pred_mean[, (n_fric_basis+1):(n_fric_basis+n_bed_basis)] * test_data$sd_bed_coefs + test_data$mean_bed_coefs
    pred_gl <- pred_mean[, (n_fric_basis+n_bed_basis+1):ncol(pred_mean)] * test_data$sd_gl + test_data$mean_gl

    if (test_on_train) {
        train_fric_coefs <- train_data$fric_coefs[1:100, ] * train_data$sd_fric_coefs + train_data$mean_fric_coefs
    }
    test_fric_coefs <- test_output[, 1:n_fric_basis] * test_data$sd_fric_coefs + test_data$mean_fric_coefs
    test_bed_coefs <- test_output[, (n_fric_basis+1):(n_fric_basis+n_bed_basis)] * test_data$sd_bed_coefs + test_data$mean_bed_coefs
    test_gl <- test_output[, (n_fric_basis+n_bed_basis+1):ncol(test_output)] * test_data$sd_gl + test_data$mean_gl

    ## Compute predicted vs original friction -- this needs more work!!
    if (log_transform) {
        pred_fric <- exp(fric_basis_mat %*% t(pred_fric_coefs))
        test_fric <- exp(fric_basis_mat %*% t(test_fric_coefs))
    } else {
        pred_fric <- fric_basis_mat %*% t(pred_fric_coefs)
        test_fric <- fric_basis_mat %*% t(test_fric_coefs)
    }

    ## Compute predicted vs original bed fluctuations (demeaned bed)
    pred_bed_demean <- bed_basis_mat %*% t(pred_bed_coefs)
    test_bed_demean <- bed_basis_mat %*% t(test_bed_coefs)


# } else {
#     stop("Output not available for this variable.")
# }


if (test_on_train) {
    par(mfrow = c(1,1))
    plot(train_fric_coefs[50,], type = "l")
    lines(pred_fric_coefs[50,], col = "red")
} else {
    par(mfrow = c(1,1))
    plot(test_fric_coefs[1,], type = "l")
    lines(pred_fric_coefs[1,], col = "red")
}


# ########### end quantile ################

## Calculate quantiles of the bed and friction based on 
## the quantiles of the basis function coefficients

# ### Friction
# z_val <- qnorm(0.95)
# fric_sd1 <- (pred_fric_coefs - pred_quantiles[[1]]$fric) / z_val # distance from mean to lower quantile
# fric_sd2 <- (pred_quantiles[[2]]$fric - pred_fric_coefs) / z_val # distance from mean to upper quantile
# fric_avg_sd <- (fric_sd1 + fric_sd2)/2 # this is the "point-wise" standard deviation 

# neg_ind <- which(fric_avg_sd < 0)
# fric_avg_sd[neg_ind] <- 1e-02
# ## Now sample lots of basis coefficients from this distribution
# ## Maybe for each test output sample, we can sample 1000 basis coefficients
# n_fric_basis <- ncol(fric_basis_mat)
# fric_coef_samples <- list()

### Bed elevation

### Add bed trend to the predicted oscillations
bed_obs <- readRDS(file = paste0("./training_data/bed_obs_", data_date, ".rds"))
df <- data.frame(obs_locations = domain[bed_obs$locations], bed_elev = bed_obs$obs)
bed.fit <- loess(bed_elev ~ obs_locations, data = df, span = 0.25, 
                    control = loess.control(surface = "direct")) 
bed_mean <- predict(bed.fit, newdata = data.frame(obs_locations = domain))
bed_mean_mat <- matrix(rep(bed_mean), nrow = length(bed_mean), ncol = ncol(pred_bed_demean))

pred_bed <- pred_bed_demean + bed_mean_mat
test_bed <- test_bed_demean + bed_mean_mat

#################################
##      Save predictions       ##
#################################

if (save_pred) {
    saveRDS(pred_fric, file = paste0(output_dir, "/pred_fric_", data_date, ".rds"))
    saveRDS(pred_bed, file = paste0(output_dir, "/pred_bed_", data_date, ".rds"))
    saveRDS(pred_gl, file = paste0(output_dir, "/pred_gl_", data_date, ".rds"))
}


######################################
##      Comparison with truth       ##
######################################

## True parameter values for comparison
true_fric <- test_data$true_fric
true_bed <- test_data$true_bed
true_gl <- test_data$true_gl #* test_data$sd_gl + test_data$mean_gl

## Scaling units for friction coefficients
# secpera <- 31556926
# fric_scale <- 1e6 * secpera^(1/3)
# true_fric <- true_fric/fric_scale

## Choose random samples from test set for plotting
samples <- sample(1:nrow(test_output), 4)

if (save_plots) {
    
    ## Friction plots
    png(paste0(plot_dir, "/pred_vs_true_fric", checkpt, ".png"), width = 2000, height = 1200)

    par(mfrow = c(length(samples) / 2, 2))
    for (i in 1:length(samples)) {
        par(mar = c(6, 8, 4, 2))
        gl <- test_data$grounding_line[i] / 800 * 2001
        plot_domain <- 1:length(domain) # ceiling(gl)

        plot(domain[plot_domain]/1000, test_fric[, i], type = "l", 
            ylab = "Friction (unit)", xlab = "Domain (km)", 
            cex.axis = 3, cex.lab = 4)
        # lines(domain[plot_domain]/1000, true_fric[i, ], col = "red")
        lines(domain[plot_domain]/1000, pred_fric[, i], col = "red")
        abline(v = test_data$test_gl[i], lty = 1, lwd = 3)
    }

    dev.off()


    ## Bed plot
    png(paste0(plot_dir, "/pred_vs_true_bed", checkpt, ".png"), width = 2000, height = 2000)
    par(mfrow = c(length(samples) / 2, 2))

    for (i in 1:length(samples)) {
        par(mar = c(6, 8, 4, 2))
        # gl <- test_data$grounding_line[i] / 800 * 2001
        plot_domain <- 1:length(domain) # ceiling(gl)
        plot(domain[plot_domain] / 1000, true_bed[i, plot_domain],
            type = "l", lwd = 2, col = "black",
            ylab = "Bed (m)", xlab = "Domain (km)", cex.axis = 3, cex.lab = 4
        )
        # lines(domain[plot_domain] / 1000, test_bed[plot_domain, i], lwd = 2, col = "blue")
        lines(domain[plot_domain] / 1000, pred_bed[plot_domain, i], lwd = 3, col = "red")
        # lines(domain[plot_domain] / 1000, bed_lq[[i]], lty = 1, lwd = 3, col = "skyblue")
        # lines(domain[plot_domain] / 1000, bed_uq[[i]], lty = 1, lwd = 3, col = "skyblue")
        
        abline(v = test_data$test_gl[i], lty = 1, lwd = 3)
    }
    dev.off()

    ## Grounding line plot
    
    png(paste0(plot_dir, "/pred_vs_true_gl", checkpt, ".png"), width = 2000, height = 2000)
    par(mfrow = c(length(samples) / 2, 2))

    for (i in 1:length(samples)) {
        par(mar = c(6, 8, 4, 2))
        # gl <- test_data$grounding_line[i] / 800 * 2001
        plot_domain <- 1:length(domain) # ceiling(gl)
        plot(true_gl[i, ], 1:20,
            type = "l", lwd = 2, 
            xlab = "Grounding line (km)", ylab = "Time (year)", cex.axis = 3, cex.lab = 4
        )
        # lines(domain[plot_domain] / 1000, test_fric[i, ], lwd = 2, col = "blue")
        lines(pred_gl[i, ], 1:20, lwd = 2, col = "red")
        # lines(pred_gl_lq[i, ], 1:20, lty = 1, lwd = 3, col = "skyblue")
        # lines(pred_gl_uq[i, ], 1:20, lty = 1, lwd = 3, col = "skyblue")
        
        # abline(v = test_data$test_gl[i], lwd = 3, lty = 2)
    }

    dev.off()

}

############################################# RMSE ##################################################
# rmse <- function(truth, pred) {
#     sqrt(mean((truth - pred)^2))
# }

# total_rmse <- 0
# if (output_var == "friction") {## Post-process output from CNN
#     truth <- test_fric
#     pred <- pred_fric
# } else if (output_var == "grounding_line") {
#    truth <- test_gl
#    pred <- pred_gl
# } else if (output_var == "bed") {
#     truth <- test_bed
#     pred <- pred_bed
# } else if (output_var == "all") {
#     truth <- cbind(test_fric, test_bed)
#     pred <- cbind(pred_fric, pred_bed)
# } else {
#     print("Output variable should be either 'friction', 'bed' or 'grounding_line'.")
# }

# for (s in 1:ncol(truth)) {
#     total_rmse <- total_rmse + rmse(truth[, s], pred[, s])
# }
# cat("RMSE: ", total_rmse / ncol(truth), "\n") # normalise by number of simulations in the test set

# # }

