## Post-process output from CNN
setwd("~/SSA_model/CNN/simbed/")

rm(list = ls())
source("./source/create_model.R")
source("./source/posterior_loss.R")
source("./source/sample_from_posterior.R")

library(parallel)
library(mvtnorm) 
library(Matrix)
library(keras)
reticulate::use_condaenv("myenv", required = TRUE)
library(tensorflow)
library(ggplot2)
library(qs)

## Flags
save_pred <- T
save_plots <- T
log_transform <- T
test_on_train <- F
use_missing_pattern <- T

## Read data
data_date <- "20240320"
sets <- 1:50 #6:20
# setf <- formatC(set, width=2, flag="0")
setsf <- paste0("sets", sets[1], "-", sets[length(sets)])

if (use_missing_pattern) {
    data_dir <- paste0("./training_data/", setsf, "/missing")
    output_dir <- paste0("./output/posterior/", setsf, "/missing")
} else {
    data_dir <- paste0("./training_data/", setsf, "/nonmissing")
    output_dir <- paste0("./output/posterior/", setsf, "/nonmissing")
}

test_data <- qread(file = paste0(data_dir, "/test_data_", data_date, ".qs"))

if (test_on_train) {
    train_data <- qread(file = paste0(data_dir, "/train_data_", data_date, ".qs"))
}

setf <- formatC(sets[1], width = 2, flag = "0")
friction_basis <- readRDS(file = paste0("./training_data/friction_basis_", setf, "_", data_date, ".rds"))
dim(friction_basis$basis_mat)      

png(paste0(output_dir, "/true_fric_1.png"), width = 2000, height = 1200)
plot(friction_basis$fitted_values[1, ], type = "l")
dev.off()

ssa_steady <- readRDS(file = paste("./training_data/initial_conds/ssa_steady_20220329.rds", sep = ""))
domain <- ssa_steady$domain

## Load the model
test_input <- test_data$input
test_output <- cbind(test_data$fric_coefs, test_data$bed_coefs, test_data$grounding_line)

input_dim <- dim(test_data$input)[2:4]
n_basis_funs <- dim(test_data$fric_coefs)[2]
n_gl <- dim(test_data$grounding_line)[2]
n_mean_elements <- n_basis_funs * 2 + n_gl
n_chol_elements <- (n_basis_funs * 2 + n_gl) + (n_basis_funs - 1) * 2 + (n_gl - 1) # diagonal + lower-diag elements
output_dim <- n_mean_elements + n_chol_elements  # THIS NEEDS TO CHANGE TO THE TOTAL NUMBER OF BASIS FUNCTIONS + COVARIANCE PARAMETERS

model <- create_model_posterior(input_dim = input_dim, 
                                output_dim = output_dim,
                                n_basis_funs = n_basis_funs,
                                n_gl = n_gl)

### Display the model's architecture
summary(model)

### Plot the loss
history <- readRDS(file = paste0(output_dir, "/history_", data_date, ".rds"))
# history %>% plot() #+
# coord_cartesian(xlim = c(1, epochs))

if (use_missing_pattern) {
    plot_dir <- paste0("./plots/posterior/", setsf, "/missing")
} else {
    plot_dir <- paste0("./plots/posterior/", setsf)

}

if (save_plots) {

    # if (!dir.exists(plot_dir)) {
    #     dir.create(plot_dir)
    # }

    png(paste0(plot_dir, "/loss.png"), width = 1000, height = 500)
    plot(history$metrics$loss[2:50], type = "l")
    lines(history$metrics$val_loss[2:50], col = "red")
    legend("topright", legend = c("Training", "Validation"), col = c("black", "red"), lty = 1, cex = 0.8)
    dev.off()
}

###################################
##        Mean prediction        ##   
###################################

## Reload model from checkpoint
checkpoint_path <- paste0(output_dir, "/checkpoints/cp-{epoch:04d}.ckpt")
checkpoint_dir <- fs::path_dir(checkpoint_path)

checkpt <- which.min(history$metrics$val_loss) 
if (!is.null(checkpt)) {
    ## Load the model from checkpt
    cp_restart <- paste0(output_dir, "/checkpoints/cp-", formatC(checkpt, width = 4, flag = "0"), ".ckpt")
    # latest <- tf$train$latest_checkpoint(checkpoint_dir)
    load_model_weights_tf(model, cp_restart)
} else { # use latest checkpt
    latest <- tf$train$latest_checkpoint(checkpoint_dir)
    load_model_weights_tf(model, latest)
}

## Predict
if (test_on_train) {
    train_subset <- train_data$input[1:100,,,]
    pred_output <- model %>% predict(train_subset)
} else {
    pred_time <- system.time({
        pred_output <- model %>% predict(test_input)
    })
    cat("Prediction time: ", pred_time[3], "\n")
}

## Plot the predicted friction coefs generated by these basis functions

fric_basis_mat <- test_data$fric_basis_mat
bed_basis_mat <- test_data$bed_basis_mat
n_fric_basis <- ncol(fric_basis_mat)
n_bed_basis <- ncol(bed_basis_mat)

pred_mean <- pred_output[, 1:n_mean_elements]

## Un-standardise output
pred_fric_coefs <- pred_mean[, 1:n_fric_basis] * test_data$sd_fric_coefs + test_data$mean_fric_coefs
pred_bed_coefs <- pred_mean[, (n_fric_basis+1):(n_fric_basis+n_bed_basis)] * test_data$sd_bed_coefs + test_data$mean_bed_coefs
pred_gl <- pred_mean[, (n_fric_basis+n_bed_basis+1):ncol(pred_mean)] * test_data$sd_gl + test_data$mean_gl

if (test_on_train) {
    train_fric_coefs <- train_data$fric_coefs[1:100, ] * train_data$sd_fric_coefs + train_data$mean_fric_coefs
}
test_fric_coefs <- test_output[, 1:n_fric_basis] * test_data$sd_fric_coefs + test_data$mean_fric_coefs
test_bed_coefs <- test_output[, (n_fric_basis+1):(n_fric_basis+n_bed_basis)] * test_data$sd_bed_coefs + test_data$mean_bed_coefs
test_gl <- test_output[, (n_fric_basis+n_bed_basis+1):ncol(test_output)] * test_data$sd_gl + test_data$mean_gl

## Compute predicted vs original friction 
if (log_transform) {
    pred_fric <- exp(fric_basis_mat %*% t(pred_fric_coefs))
    test_fric <- exp(fric_basis_mat %*% t(test_fric_coefs))
} else {
    pred_fric <- fric_basis_mat %*% t(pred_fric_coefs)
    test_fric <- fric_basis_mat %*% t(test_fric_coefs)
}

## Compute predicted vs original bed fluctuations (demeaned bed)
pred_bed_demean <- bed_basis_mat %*% t(pred_bed_coefs)
test_bed_demean <- bed_basis_mat %*% t(test_bed_coefs)

if (test_on_train) {
    par(mfrow = c(1,1))
    plot(train_fric_coefs[50,], type = "l")
    lines(pred_fric_coefs[50,], col = "red")
} else {
    par(mfrow = c(1,1))
    plot(test_fric_coefs[1,], type = "l")
    lines(pred_fric_coefs[1,], col = "red")
}

### Reconstruct bed elevation by adding bed trend to the predicted oscillations
bed_obs <- readRDS(file = paste0("./training_data/bed_obs_", data_date, ".rds"))
df <- data.frame(obs_locations = domain[bed_obs$locations], bed_elev = bed_obs$obs)
bed.fit <- loess(bed_elev ~ obs_locations, data = df, span = 0.25, 
                    control = loess.control(surface = "direct")) 
bed_mean <- predict(bed.fit, newdata = data.frame(obs_locations = domain))
bed_mean_mat <- matrix(rep(bed_mean), nrow = length(bed_mean), ncol = ncol(pred_bed_demean))

pred_bed <- pred_bed_demean + bed_mean_mat
test_bed <- test_bed_demean + bed_mean_mat

## Covariance matrix
pred_chol <- pred_output[, (n_mean_elements+1):ncol(pred_output)]

## Construct Cholesky factor of the precision
Lb_elems <- n_basis_funs + (n_basis_funs - 1)
Lc_elems <- n_basis_funs + (n_basis_funs - 1)
Lg_elems <- n_gl + (n_gl - 1)

Lmats <- list()
for (s in 1:nrow(pred_chol)) {
    Lb <- construct_L_matrix(pred_chol[s, 1:Lb_elems], n_basis_funs)
    Lc <- construct_L_matrix(pred_chol[s, (Lb_elems+1):(Lb_elems+Lc_elems)], n_basis_funs)
    Lg <- construct_L_matrix(pred_chol[s, (Lb_elems+Lc_elems+1):(Lb_elems+Lc_elems+Lg_elems)], n_gl)
    Lmats[[s]] <- bdiag(Lb, Lc, Lg)
}

# ## Need to sample from the posterior distribution of the coefs
# ## then transform them to actual friction, bed, gl
print("Sampling from the posterior distribution...")
S <- 1000 ## number of posterior samples

fric_samples_ls2 <- list()
bed_samples_ls2 <- list()
gl_samples_ls2 <- list()

fric_lq2 <- list()
fric_uq2 <- list()
bed_lq2 <- list()
bed_uq2 <- list()
gl_lq2 <- list()
gl_uq2 <- list()

## Sample basis function coefficients from posterior
sampletime1 <- system.time({
pred_samples_ls <- lapply(1:nrow(test_output), function(i) 
                            sample_from_posterior(n = S, mean = pred_mean[i, ], prec_chol = Lmats[[i]])) #,
                                # mc.cores = 10L)
                                

## Transform basis coefficients into actual friction coefficients
sd_fric_coefs <- test_data$sd_fric_coefs
mean_fric_coefs <- test_data$mean_fric_coefs

s2 <- system.time({
    fric_samples_ls <- lapply(pred_samples_ls, function(x, log_transform, mean_fric_coefs, sd_fric_coefs) { 
    fric_coefs <- x[1:n_fric_basis, ]
    fric_coefs_ustd <- fric_coefs * sd_fric_coefs + mean_fric_coefs
    
    # if (log_transform) {
        fric_samples <- exp(fric_basis_mat %*% fric_coefs_ustd)
    # } else {
        # fric_samples <- fric_basis_mat %*% fric_coefs_ustd
    # }
    return(fric_samples)
    }, 
    log_transform = log_transform,
    mean_fric_coefs = mean_fric_coefs,
    sd_fric_coefs = sd_fric_coefs#,
    # mc.cores = 4L
)

})


## Transform basis coefficients into bed elevations
bed_mean_mat <- matrix(rep(bed_mean), nrow = length(bed_mean), ncol = S)
s3 <- system.time({
bed_samples_ls <- lapply(pred_samples_ls, function(x) {
    bed_coefs <- x[(n_fric_basis+1):(n_fric_basis+n_bed_basis), ]
    bed_coefs_ustd <- bed_coefs * test_data$sd_bed_coefs + test_data$mean_bed_coefs
    bed_samples <- bed_basis_mat %*% bed_coefs_ustd + bed_mean_mat
    }
)

})

## Grounding line is a direct output from the CNN
gl_samples_ls <- lapply(pred_samples_ls, function(x) x[(n_fric_basis+n_bed_basis+1):n_mean_elements, ])

## Compute quantiles
s5 <- system.time({
    fric_q <- lapply(fric_samples_ls, function(x) apply(x, 1, quantile, probs = c(0.025, 0.975)))
    bed_q <- lapply(bed_samples_ls, function(x) apply(x, 1, quantile, probs = c(0.025, 0.975)))
    gl_q <- lapply(gl_samples_ls, function(x) apply(x, 1, quantile, probs = c(0.025, 0.975)))
})

fric_lq <- lapply(fric_q, function(x) x[1, ])
fric_uq <- lapply(fric_q, function(x) x[2, ])
bed_lq <- lapply(bed_q, function(x) x[1, ])
bed_uq <- lapply(bed_q, function(x) x[2, ])
gl_lq <- lapply(gl_q, function(x) x[1, ])
gl_uq <- lapply(gl_q, function(x) x[2, ])
})

# sampletime2 <- system.time({
#     for (s in 1:100) { # parallelise this later

#     cat("Sample: ", s, "\n")
#     L <- Lmats[[s]]

#     ### Sample from the posterior distribution
#     z <- matrix(rnorm(S * n_mean_elements), 
#                 nrow = n_mean_elements, ncol = S)
#     v <- backsolve(L, z)

#     meanmat <- matrix(rep(pred_mean[s, ], S), 
#                 nrow = n_mean_elements, ncol = S)
#     pred_samples <- meanmat + v

#     ## Un-standardise output
#     ## Then dissect the pred samples to get the friction, bed, gl
#     fric_coef_samples <- pred_samples[1:n_fric_basis, ]
#     bed_coef_samples <- pred_samples[(n_fric_basis+1):(n_fric_basis+n_bed_basis), ]
#     gl_samples <- pred_samples[(n_fric_basis+n_bed_basis+1):n_mean_elements, ]

#     fric_coef_samples_ustd <- fric_coef_samples * test_data$sd_fric_coefs + test_data$mean_fric_coefs
#     bed_coef_samples_ustd <- bed_coef_samples * test_data$sd_bed_coefs + test_data$mean_bed_coefs
#     gl_samples_ustd <- gl_samples * test_data$sd_gl + test_data$mean_gl

#     ## Compute friction samples  
#     if (log_transform) {
#         fric_samples_ls2[[s]] <- exp(fric_basis_mat %*% fric_coef_samples_ustd)
#     } else {
#         fric_samples_ls2[[s]] <- fric_basis_mat %*% fric_coef_samples_ustd
#     }

#     bed_samples_ls2[[s]] <- bed_basis_mat %*% bed_coef_samples_ustd + bed_mean_mat
#     gl_samples_ls2[[s]] <- gl_samples_ustd

#     fric_lq2[[s]] <- apply(fric_samples_ls[[s]], 1, quantile, probs = 0.025)
#     fric_uq2[[s]] <- apply(fric_samples_ls[[s]], 1, quantile, probs = 0.975)
    
#     bed_lq2[[s]] <- apply(bed_samples_ls[[s]], 1, quantile, probs = 0.025)
#     bed_uq2[[s]] <- apply(bed_samples_ls[[s]], 1, quantile, probs = 0.975)

#     gl_lq2[[s]] <- apply(gl_samples_ls[[s]], 1, quantile, probs = 0.025)
#     gl_uq2[[s]] <- apply(gl_samples_ls[[s]], 1, quantile, probs = 0.975)
# }

# })

# png(paste0(plot_dir, "/fric_coef_samples", checkpt, ".png"), width = 2000, height = 1200)
# matplot(fric_coef_samples_ustd[, 1:10], col = "grey", type = "l")
# lines(pred_fric_coefs[s, ], col = "red", lwd = 2)
# dev.off()


#################################
##      Save predictions       ##
#################################

if (save_pred) {
    qsave(pred_fric, file = paste0(output_dir, "/pred_fric_", data_date, ".qs"))
    qsave(pred_bed, file = paste0(output_dir, "/pred_bed_", data_date, ".qs"))
    qsave(pred_gl, file = paste0(output_dir, "/pred_gl_", data_date, ".qs"))
    qsave(Lmats, file = paste0(output_dir, "/Lmats_", data_date, ".qs"))
    # saveRDS(fric_samples_ls, file = paste0(output_dir, "/fric_post_samples_", data_date, ".rds"))
    # saveRDS(bed_samples_ls, file = paste0(output_dir, "/bed_post_samples_", data_date, ".rds"))
    # saveRDS(gl_samples_ls, file = paste0(output_dir, "/gl_post_samples_", data_date, ".rds"))
    qsave(fric_samples_ls, file = paste0(output_dir, "/fric_post_samples_", data_date, ".qs"))
    qsave(bed_samples_ls, file = paste0(output_dir, "/bed_post_samples_", data_date, ".qs"))
    qsave(gl_samples_ls, file = paste0(output_dir, "/gl_post_samples_", data_date, ".qs"))

    # saveRDS(fric_lq, file = paste0(output_dir, "/fric_lq_", data_date, ".rds"))
    # saveRDS(fric_uq, file = paste0(output_dir, "/fric_uq_", data_date, ".rds"))
    # saveRDS(bed_lq, file = paste0(output_dir, "/bed_lq_", data_date, ".rds"))
    # saveRDS(bed_uq, file = paste0(output_dir, "/bed_uq_", data_date, ".rds"))
    # saveRDS(gl_lq, file = paste0(output_dir, "/gl_lq_", data_date, ".rds"))
    # saveRDS(gl_uq, file = paste0(output_dir, "/gl_uq_", data_date, ".rds"))
} else {
    pred_fric <- qread(file = paste0(output_dir, "/pred_fric_", data_date, ".qs"))
    pred_bed <- qread(file = paste0(output_dir, "/pred_bed_", data_date, ".qs"))
    pred_gl <- qread(file = paste0(output_dir, "/pred_gl_", data_date, ".qs"))
    Lmats <- qread(file = paste0(output_dir, "/Lmats_", data_date, ".qs"))
    
    fric_samples_ls <- qread(file = paste0(output_dir, "/fric_post_samples_", data_date, ".qs"))
    bed_samples_ls <- qread(file = paste0(output_dir, "/bed_post_samples_", data_date, ".qs"))
    gl_samples_ls <- qread(file = paste0(output_dir, "/gl_post_samples_", data_date, ".qs"))

}

######################################
##      Comparison with truth       ##
######################################

## True parameter values for comparison
true_fric <- test_data$true_fric
true_bed <- test_data$true_bed
true_gl <- test_data$true_gl #* test_data$sd_gl + test_data$mean_gl

## Scaling units for friction coefficients
# secpera <- 31556926
# fric_scale <- 1e6 * secpera^(1/3)
# true_fric <- true_fric/fric_scale

## Choose random samples from test set for comparison
samples <- sample(1:nrow(test_output), 6)

if (save_plots) {
    
    ## Friction plots
    png(paste0(plot_dir, "/pred_vs_true_fric", checkpt, ".png"), width = 2000, height = 1200)

    plot_domain <- 1:1200 #length(domain) # ceiling(gl)

    par(mfrow = c(length(samples) / 2, 2))
    # for (i in 1:length(samples)) {
    for (s in samples) {
        # s <- samples[i]
        par(mar = c(6, 8, 4, 2))
        gl <- test_data$grounding_line[s] / 800 * 2001

        plot(domain[plot_domain]/1000, test_fric[plot_domain, s], type = "l", 
            ylab = "Friction (unit)", xlab = "Domain (km)", 
            cex.axis = 3, cex.lab = 4)
        matlines(domain[plot_domain]/1000, fric_samples_ls[[s]][plot_domain, 1:3], 
                    lty = 1, lwd = 3, col = adjustcolor("mediumpurple", alpha = 0.5))
        # lines(domain[plot_domain]/1000, true_fric[i, ], col = "red")
        lines(domain[plot_domain]/1000, pred_fric[plot_domain, s], col = "red")
        lines(domain[plot_domain]/1000, fric_lq[[s]][plot_domain], lty = 1, lwd = 3, col = "grey")
        lines(domain[plot_domain]/1000, fric_uq[[s]][plot_domain], lty = 1, lwd = 3, col = "grey")
        
        
        abline(v = test_data$true_gl[s, 1], lty = 2, lwd = 3)
    }

    dev.off()


    ## Bed plot
    png(paste0(plot_dir, "/pred_vs_true_bed", checkpt, ".png"), width = 2000, height = 2000)
    par(mfrow = c(length(samples) / 2, 2))

    # for (i in 1:length(samples)) {
    for (s in samples) {
        # s <- samples[i]
        par(mar = c(6, 8, 4, 2))
        # gl <- test_data$grounding_line[i] / 800 * 2001
        plot(domain[plot_domain] / 1000, test_bed[plot_domain, s],
            type = "l", lwd = 2, col = "black",
            ylab = "Bed (m)", xlab = "Domain (km)", cex.axis = 3, cex.lab = 4
        )
        # lines(domain[plot_domain] / 1000, test_bed[plot_domain, i], lwd = 2, col = "blue")
        matlines(domain[plot_domain]/1000, bed_samples_ls[[s]][plot_domain, 1:3], 
                lty = 1, lwd = 3, col = adjustcolor("mediumpurple", alpha = 0.5))
        lines(domain[plot_domain] / 1000, pred_bed[plot_domain, s], lwd = 3, col = "red")
        lines(domain[plot_domain] / 1000, bed_lq[[s]][plot_domain], lty = 1, lwd = 3, col = "grey")
        lines(domain[plot_domain] / 1000, bed_uq[[s]][plot_domain], lty = 1, lwd = 3, col = "grey")
        
        abline(v = test_data$true_gl[s, 1], lty = 2, lwd = 3)
    }
    dev.off()

    ## Grounding line plot
    
    png(paste0(plot_dir, "/pred_vs_true_gl", checkpt, ".png"), width = 2000, height = 2000)
    par(mfrow = c(length(samples) / 2, 2))
    
    # for (i in 1:length(samples)) {
    for (s in samples) {
        # s <- samples[i]
        par(mar = c(6, 8, 4, 2))
        # gl <- test_data$grounding_line[i] / 800 * 2001
        plot_domain <- 1:length(domain) # ceiling(gl)
        plot(true_gl[s, ], 1:20,
            type = "l", lwd = 2, 
            xlab = "Grounding line (km)", ylab = "Time (year)", cex.axis = 3, cex.lab = 4
        )
        matlines(gl_samples_ls[[s]][, 1:3], 1:20, lty = 1, lwd = 3, col = adjustcolor("mediumpurple", alpha = 0.5))
        # lines(domain[plot_domain] / 1000, test_fric[i, ], lwd = 2, col = "blue")
        lines(pred_gl[s, ], 1:20, lwd = 2, col = "red")
        lines(gl_lq[[s]], 1:20, lty = 1, lwd = 3, col = "grey")
        lines(gl_uq[[s]], 1:20, lty = 1, lwd = 3, col = "grey")
        
        # abline(v = test_data$test_gl[i], lwd = 3, lty = 2)
    }

    dev.off()

}

############################################# RMSE ##################################################
# rmse <- function(truth, pred) {
#     sqrt(mean((truth - pred)^2))
# }

# total_rmse <- 0
# if (output_var == "friction") {## Post-process output from CNN
#     truth <- test_fric
#     pred <- pred_fric
# } else if (output_var == "grounding_line") {
#    truth <- test_gl
#    pred <- pred_gl
# } else if (output_var == "bed") {
#     truth <- test_bed
#     pred <- pred_bed
# } else if (output_var == "all") {
#     truth <- cbind(test_fric, test_bed)
#     pred <- cbind(pred_fric, pred_bed)
# } else {
#     print("Output variable should be either 'friction', 'bed' or 'grounding_line'.")
# }

# for (s in 1:ncol(truth)) {
#     total_rmse <- total_rmse + rmse(truth[, s], pred[, s])
# }
# cat("RMSE: ", total_rmse / ncol(truth), "\n") # normalise by number of simulations in the test set

# # }

