## Post-process output from CNN
setwd("/home/babv971/SSA_model/CNN/pilot")

rm(list = ls())

# library(keras)
# reticulate::use_condaenv("myenv", required = TRUE)
# library(tensorflow)
# library(ggplot2)

## Read data
data_date <- "20240320"
set <- 1

ssa_steady <- readRDS(file = paste("./training_data/initial_conds/ssa_steady_20220329.rds", sep = ""))
domain <- ssa_steady$domain

## Plot the predicted friction coefs generated by these basis functions
## And compare them to the original friction coefs ---- move to separate file later
pred_coefs <- readRDS(file = paste0("./output/pred_coefs_", set, "_", data_date, ".rds"))
train_data <- readRDS(file = paste0("./training_data/train_data_", data_date, ".rds"))
test_coefs <- train_data$test_output

## Matrix of basis functions
fric_basis <- readRDS(file = paste0("./training_data/friction_basis_", set, "_", data_date, ".rds"))
basis_mat <- fric_basis$basis_mat

## Compute predicted vs original friction coefficients
pred_fric <- basis_mat %*% t(pred_coefs)
test_fric <- basis_mat %*% t(test_coefs)
# matplot(pred_fric, type = "l")

par(mfrow = c(nrow(pred_coefs)/2, 2))

for (i in 1:nrow(pred_coefs)) {
    plot(domain/1000, test_fric[, i], type = "l", lwd = 2, ylab = "Friction (unit)", xlab = "Domain (km)")
    lines(domain/1000, pred_fric[, i], col = "red", lwd = 2)
}

## Model diagnostics
model <- readRDS(file = paste0("./output/cnn_model_", set, "_", data_date, ".rds"))
        